"""Tests for HaFloorsSyncAPIView helper functions.

Validates floor ID generation and the controller's sync / rollback logic
without requiring a live Home Assistant instance.
"""

import importlib.util
import sys
import types
from pathlib import Path

# ---------------------------------------------------------------------------
# Minimal stub setup — load only the controller module under test
# ---------------------------------------------------------------------------

base_dir = Path(__file__).resolve().parents[1]

# Stub aiohttp
aiohttp_module = types.ModuleType("aiohttp")
web_module = types.ModuleType("aiohttp.web")
web_module.Request = object  # type: ignore[attr-defined]
web_module.Response = object  # type: ignore[attr-defined]
aiohttp_module.web = web_module  # type: ignore[attr-defined]
sys.modules.setdefault("aiohttp", aiohttp_module)
sys.modules.setdefault("aiohttp.web", web_module)

# Stub homeassistant packages
for mod_name in [
    "homeassistant",
    "homeassistant.components",
    "homeassistant.components.http",
]:
    sys.modules.setdefault(mod_name, types.ModuleType(mod_name))


class _FakeHAView:
    requires_auth = True


ha_http = sys.modules["homeassistant.components.http"]
ha_http.HomeAssistantView = _FakeHAView  # type: ignore[attr-defined]

# Stub the base controller module
base_ctrl_stub = types.ModuleType(
    "custom_components.device_manager.controllers.base"
)


class _BaseView(_FakeHAView):
    def json(self, result, status_code=200):
        return {"result": result, "status": status_code}


base_ctrl_stub.BaseView = _BaseView  # type: ignore[attr-defined]
base_ctrl_stub.get_repos = lambda req: {}  # type: ignore[attr-defined]
base_ctrl_stub.csrf_protect = lambda f: f  # type: ignore[attr-defined]

sys.modules["custom_components"] = types.ModuleType("custom_components")
sys.modules["custom_components.device_manager"] = types.ModuleType(
    "custom_components.device_manager"
)
sys.modules["custom_components.device_manager.controllers"] = types.ModuleType(
    "custom_components.device_manager.controllers"
)
sys.modules[
    "custom_components.device_manager.controllers.base"
] = base_ctrl_stub

# Now load the actual module under test
ctrl_path = base_dir / "controllers" / "ha_floors_controller.py"
spec = importlib.util.spec_from_file_location(
    "ha_floors_controller", str(ctrl_path)
)
assert spec is not None and spec.loader is not None
ctrl_module = importlib.util.module_from_spec(spec)
ctrl_module.__package__ = "custom_components.device_manager.controllers"
spec.loader.exec_module(ctrl_module)  # type: ignore[union-attr]

HaFloorsSyncAPIView = ctrl_module.HaFloorsSyncAPIView


# ---------------------------------------------------------------------------
# Registry stub that mirrors the real HA FloorRegistry API (HA 2024.4+)
#
# Real signatures (from homeassistant/helpers/floor_registry.py):
#   async_create(name, *, aliases=None, icon=None, level=None) -> FloorEntry
#   async_get_floor_by_name(name) -> FloorEntry | None
#   async_get_floor(floor_id) -> FloorEntry | None
#   async_update(floor_id, *, name=UNDEFINED, level=UNDEFINED, ...) -> FloorEntry
#   async_delete(floor_id) -> None
#
# floor_id is auto-generated by _generate_id(name) — callers cannot set it.
# ---------------------------------------------------------------------------


class _FakeFloorEntry:
    """Minimal stub of HA FloorEntry."""

    def __init__(self, floor_id: str, name: str, level):
        self.floor_id = floor_id
        self.name = name
        self.level = level


def _auto_id(name: str) -> str:
    """Mimic HA's _generate_id: slugify the name."""
    import re
    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")


class _FakeRegistry:
    """Minimal stub of HA FloorRegistry for rollback testing."""

    def __init__(self):
        self.floors: dict[str, _FakeFloorEntry] = {}
        self.deleted: list[str] = []
        self.updated: list[tuple] = []

    def async_get_floor_by_name(self, name: str):
        for entry in self.floors.values():
            if entry.name == name:
                return entry
        return None

    def async_get_floor(self, floor_id: str):
        return self.floors.get(floor_id)

    def async_create(self, name: str, *, level=None, **_kw):
        """Auto-generate floor_id from name, exactly like HA."""
        floor_id = _auto_id(name)
        entry = _FakeFloorEntry(floor_id, name, level)
        self.floors[floor_id] = entry
        return entry

    def async_update(self, floor_id: str, *, name=None, level=None, **_kw):
        if floor_id in self.floors:
            if name is not None:
                self.floors[floor_id].name = name
            if level is not None:
                self.floors[floor_id].level = level
        self.updated.append((floor_id, name, level))

    def async_delete(self, floor_id: str):
        self.floors.pop(floor_id, None)
        self.deleted.append(floor_id)


# ---------------------------------------------------------------------------
# Tests as plain functions for run_tests.py compatibility
# ---------------------------------------------------------------------------


def test_registry_create_auto_generates_id():
    """async_create auto-generates floor_id from the name (no external setter)."""
    registry = _FakeRegistry()
    entry = registry.async_create("Ground Floor", level=0)
    assert entry.floor_id == "ground_floor"
    assert entry.name == "Ground Floor"
    assert entry.level == 0


def test_registry_get_floor_by_name_found():
    """async_get_floor_by_name returns the correct entry."""
    registry = _FakeRegistry()
    registry.async_create("Level 1", level=1)
    result = registry.async_get_floor_by_name("Level 1")
    assert result is not None
    assert result.floor_id == "level_1"


def test_registry_get_floor_by_name_missing():
    """async_get_floor_by_name returns None when the name is not found."""
    registry = _FakeRegistry()
    assert registry.async_get_floor_by_name("Does Not Exist") is None


def test_rollback_deletes_created_floors():
    """When a 'create' action is rolled back, the floor must be deleted."""
    registry = _FakeRegistry()
    entry = registry.async_create("Ground", level=0)

    view = HaFloorsSyncAPIView.__new__(HaFloorsSyncAPIView)
    applied = [("create", entry.floor_id, None)]
    view._rollback(registry, applied)

    assert entry.floor_id in registry.deleted


def test_rollback_restores_updated_floors():
    """When an 'update' action is rolled back, the original values are restored."""
    registry = _FakeRegistry()
    entry = registry.async_create("Level 1", level=3)
    original = _FakeFloorEntry(entry.floor_id, "Level 1", 99)
    registry.async_update(entry.floor_id, name="Level 1", level=1)

    view = HaFloorsSyncAPIView.__new__(HaFloorsSyncAPIView)
    applied = [("update", entry.floor_id, original)]
    view._rollback(registry, applied)

    assert any(
        fid == entry.floor_id and name == "Level 1" and level == 99
        for fid, name, level in registry.updated
    )


def test_rollback_is_reversed_order():
    """Rollback applies changes in reverse order (last-in first-out)."""
    calls: list[str] = []

    class _TrackedRegistry(_FakeRegistry):
        def async_delete(self, floor_id):
            calls.append(f"delete:{floor_id}")
            super().async_delete(floor_id)

        def async_update(self, floor_id, *, name=None, level=None, **kw):
            calls.append(f"update:{floor_id}")
            super().async_update(floor_id, name=name, level=level)

    registry = _TrackedRegistry()
    e0 = registry.async_create("Ground", level=0)
    e1 = registry.async_create("Level 1", level=1)
    original_l1 = _FakeFloorEntry(e1.floor_id, "Level 1", 5)

    view = HaFloorsSyncAPIView.__new__(HaFloorsSyncAPIView)
    applied = [
        ("create", e0.floor_id, None),
        ("update", e1.floor_id, original_l1),
    ]
    view._rollback(registry, applied)

    # update (Level 1) must be processed before delete (Ground)
    assert calls == [f"update:{e1.floor_id}", f"delete:{e0.floor_id}"]


def test_rollback_skips_update_without_original():
    """A rollback for 'update' with no original snapshot does nothing."""
    calls: list[str] = []

    class _TrackedRegistry(_FakeRegistry):
        def async_update(self, floor_id, *, name=None, level=None, **kw):
            calls.append(f"update:{floor_id}")
            super().async_update(floor_id, name=name, level=level)

    view = HaFloorsSyncAPIView.__new__(HaFloorsSyncAPIView)
    applied = [("update", "some_floor", None)]  # no original snapshot
    view._rollback(_TrackedRegistry(), applied)

    assert calls == []


def test_rollback_tolerates_registry_error():
    """Rollback must not raise even if the registry raises on async_delete."""

    class _FailingRegistry:
        def async_delete(self, floor_id):
            raise RuntimeError("delete failed")

        def async_update(self, *a, **kw):
            pass

    view = HaFloorsSyncAPIView.__new__(HaFloorsSyncAPIView)
    view._rollback(_FailingRegistry(), [("create", "ground", None)])


def test_create_entry_floor_id_is_accessible():
    """The entry returned by async_create exposes floor_id for use in applied list."""
    registry = _FakeRegistry()
    entry = registry.async_create("Attic", level=2)
    assert entry.floor_id is not None
    assert len(entry.floor_id) > 0
    assert registry.async_get_floor_by_name("Attic") is not None


def test_ha_name_per_building_is_unique():
    """Floors in different buildings with the same name produce distinct HA names."""
    # "Home - Lvl0" vs "Erwan - Lvl0" must not collide
    home_l0 = "Home - Lvl0"
    erwan_l0 = "Erwan - Lvl0"
    assert home_l0 != erwan_l0


def test_level_resets_per_building():
    """Each building's floors are numbered from 0 independently.

    Home: Lvl0 → 0, Lvl1 → 1
    Erwan: Lvl0 → 0, Lvl1 → 1
    """
    registry = _FakeRegistry()
    # Simulate what the controller does: iterate buildings, then floors per building

    buildings = [("Home", ["Lvl0", "Lvl1"]), ("Erwan", ["Lvl0", "Lvl1"])]
    synced = []
    for building_name, floor_names in buildings:
        for idx, floor_name in enumerate(floor_names):
            ha_name = f"{building_name} - {floor_name}"
            entry = registry.async_create(ha_name, level=idx)
            synced.append({"name": ha_name, "level": idx})

    # Home floors
    assert synced[0] == {"name": "Home - Lvl0", "level": 0}
    assert synced[1] == {"name": "Home - Lvl1", "level": 1}
    # Erwan floors — level resets to 0
    assert synced[2] == {"name": "Erwan - Lvl0", "level": 0}
    assert synced[3] == {"name": "Erwan - Lvl1", "level": 1}
