"""Tests for HaRoomsSyncAPIView helper functions.

Validates the controller's sync / rollback logic without requiring a live
Home Assistant instance.
"""

import sys
import types

import helpers  # provided via sys.path by run_tests.py

# ---------------------------------------------------------------------------
# Minimal stub setup — load only the controller module under test
# ---------------------------------------------------------------------------

helpers.stub_ha_modules()
helpers.stub_aiohttp()


class _FakeHAView:
    requires_auth = True


ha_http = sys.modules["homeassistant.components.http"]
ha_http.HomeAssistantView = _FakeHAView  # type: ignore[attr-defined]

# Stub the base controller module
base_ctrl_stub = types.ModuleType(
    "custom_components.device_manager.controllers.base"
)


class _BaseView(_FakeHAView):
    def json(self, result, status_code=200):
        return {"result": result, "status": status_code}


base_ctrl_stub.BaseView = _BaseView  # type: ignore[attr-defined]
base_ctrl_stub.get_repos = lambda req: {}  # type: ignore[attr-defined]
base_ctrl_stub.csrf_protect = lambda f: f  # type: ignore[attr-defined]

async def _noop_emit(*args, **kwargs):
    pass


base_ctrl_stub.emit_activity_log = _noop_emit  # type: ignore[attr-defined]

sys.modules["custom_components"] = types.ModuleType("custom_components")
sys.modules["custom_components.device_manager"] = types.ModuleType(
    "custom_components.device_manager"
)
sys.modules["custom_components.device_manager.controllers"] = types.ModuleType(
    "custom_components.device_manager.controllers"
)
sys.modules[
    "custom_components.device_manager.controllers.base"
] = base_ctrl_stub

# Now load the actual module under test
ctrl_module = helpers.load_module(
    "controllers/ha_rooms_controller.py",
    package="custom_components.device_manager.controllers",
    module_name="ha_rooms_controller",
)

HaRoomsSyncAPIView = ctrl_module.HaRoomsSyncAPIView
_compute_area_id = ctrl_module._compute_area_id
_slugify = ctrl_module._slugify


# ---------------------------------------------------------------------------
# Area registry stub that mirrors the real HA AreaRegistry API
#
# Real signatures (from homeassistant/helpers/area_registry.py):
#   async_create(name, *, aliases=None, floor_id=None, icon=None, ...) -> AreaEntry
#   async_get_area_by_name(name) -> AreaEntry | None
#   async_get_area(area_id) -> AreaEntry | None
#   async_update(area_id, *, name=UNDEFINED, floor_id=UNDEFINED, ...) -> AreaEntry
#   async_delete(area_id) -> None
#
# area.id is auto-generated by _generate_id(name).
# ---------------------------------------------------------------------------


class _FakeAreaEntry:
    """Minimal stub of HA AreaEntry."""

    def __init__(self, area_id: str, name: str, floor_id: str | None = None):
        self.id = area_id
        self.name = name
        self.floor_id = floor_id


def _auto_id(name: str) -> str:
    """Mimic HA's _generate_id: slugify the name."""
    import re
    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")


class _FakeAreaRegistry:
    """Minimal stub of HA AreaRegistry for rollback testing."""

    def __init__(self):
        self.areas: dict[str, _FakeAreaEntry] = {}
        self.deleted: list[str] = []
        self.updated: list[tuple] = []

    def async_get_area_by_name(self, name: str):
        for entry in self.areas.values():
            if entry.name == name:
                return entry
        return None

    def async_get_area(self, area_id: str):
        return self.areas.get(area_id)

    def async_create(self, name: str, *, floor_id=None, **_kw):
        """Auto-generate area id from name, exactly like HA."""
        area_id = _auto_id(name)
        entry = _FakeAreaEntry(area_id, name, floor_id)
        self.areas[area_id] = entry
        return entry

    def async_update(self, area_id: str, *, name=None, floor_id=None, **_kw):
        if area_id in self.areas:
            if name is not None:
                self.areas[area_id].name = name
            if floor_id is not None:
                self.areas[area_id].floor_id = floor_id
        self.updated.append((area_id, name, floor_id))

    def async_delete(self, area_id: str):
        self.areas.pop(area_id, None)
        self.deleted.append(area_id)


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


def test_compute_area_id_basic():
    """_compute_area_id produces a stable slug from the full path."""
    area_id = _compute_area_id("Building A", "Floor 1", "Living Room")
    assert area_id == "building_a_floor_1_living_room"


def test_slugify_fallback_ascii():
    """_slugify regex fallback works for plain ASCII names."""
    assert _slugify("Hello World") == "hello_world"


def test_compute_area_id_special_chars():
    """_compute_area_id replaces special chars with underscores."""
    area_id = _compute_area_id("Maison", "RDC", "Cuisine")
    # Verify it's a valid slug (lowercase, no spaces)
    import re
    assert re.match(r"^[a-z0-9_]+$", area_id)


def test_registry_create_auto_generates_id():
    """async_create auto-generates area id from the name."""
    registry = _FakeAreaRegistry()
    entry = registry.async_create("Building A - Floor 1 - Living Room")
    assert entry.id == "building_a_floor_1_living_room"
    assert entry.name == "Building A - Floor 1 - Living Room"
    assert entry.floor_id is None


def test_registry_create_then_update_name_keeps_id():
    """After create+update, the area ID is stable and name reflects the update."""
    registry = _FakeAreaRegistry()
    entry = registry.async_create("Building A - Floor 1 - Kitchen", floor_id="floor_1")
    original_id = entry.id
    registry.async_update(original_id, name="Kitchen")
    # ID unchanged, display name updated
    updated = registry.async_get_area(original_id)
    assert updated is not None
    assert updated.id == original_id
    assert updated.name == "Kitchen"


def test_compute_area_id_matches_registry_create_id():
    """_compute_area_id must match the ID auto-generated by async_create."""
    registry = _FakeAreaRegistry()
    entry = registry.async_create("Maison - RDC - Bureau")
    computed = _compute_area_id("Maison", "RDC", "Bureau")
    assert entry.id == computed


def test_registry_create_with_floor_id():
    """async_create stores the floor_id."""
    registry = _FakeAreaRegistry()
    entry = registry.async_create("Building A - Floor 1 - Kitchen", floor_id="floor_1")
    assert entry.floor_id == "floor_1"


def test_registry_get_area_by_id_found():
    """async_get_area returns the correct entry when looked up by stable ID."""
    registry = _FakeAreaRegistry()
    entry = registry.async_create("Building A - Floor 1 - Office", floor_id="floor_1")
    unique_id = _compute_area_id("Building A", "Floor 1", "Office")
    result = registry.async_get_area(unique_id)
    assert result is not None
    assert result.id == entry.id


def test_registry_get_area_by_name_missing():
    """async_get_area_by_name returns None when the name is not found."""
    registry = _FakeAreaRegistry()
    assert registry.async_get_area_by_name("Does Not Exist") is None


def test_registry_get_area_missing():
    """async_get_area returns None when the ID is not found."""
    registry = _FakeAreaRegistry()
    assert registry.async_get_area("nonexistent_id") is None


def test_duplicate_name_detection():
    """When two rooms share the same name, the set of duplicates is non-empty."""
    names = ["Bath", "Kitchen", "Bath", "Office"]
    duplicate_names = {n for n in names if names.count(n) > 1}
    assert "Bath" in duplicate_names
    assert "Kitchen" not in duplicate_names
    assert "Office" not in duplicate_names


def test_unique_name_not_marked_duplicate():
    """Rooms with unique names across all floors are not in the duplicate set."""
    names = ["Bath", "Kitchen", "Office", "Garden"]
    duplicate_names = {n for n in names if names.count(n) > 1}
    assert not duplicate_names


def test_rollback_deletes_created_areas():
    """When a 'create' action is rolled back, the area must be deleted."""
    registry = _FakeAreaRegistry()
    entry = registry.async_create("Building - Floor - Room A", floor_id="floor_1")

    view = HaRoomsSyncAPIView.__new__(HaRoomsSyncAPIView)
    applied = [("create", entry.id, None)]
    view._rollback(registry, applied)

    assert entry.id in registry.deleted
    assert entry.id not in registry.areas


def test_rollback_restores_updated_areas():
    """When an 'update' action is rolled back, the original values are restored."""
    registry = _FakeAreaRegistry()
    entry = registry.async_create("Building - Floor - Room B", floor_id="floor_old")
    original = _FakeAreaEntry(entry.id, "Building - Floor - Room B", "floor_old")
    registry.async_update(entry.id, name="Building - Floor - Room B", floor_id="floor_new")

    view = HaRoomsSyncAPIView.__new__(HaRoomsSyncAPIView)
    applied = [("update", entry.id, original)]
    view._rollback(registry, applied)

    assert any(
        aid == entry.id and fid == "floor_old"
        for aid, _name, fid in registry.updated
        if aid == entry.id
    )


def test_rollback_is_reversed_order():
    """Rollback applies changes in reverse order (last-in first-out)."""
    calls: list[str] = []

    class _TrackedRegistry(_FakeAreaRegistry):
        def async_delete(self, area_id):
            calls.append(f"delete:{area_id}")
            super().async_delete(area_id)

        def async_update(self, area_id, *, name=None, floor_id=None, **kw):
            calls.append(f"update:{area_id}")
            super().async_update(area_id, name=name, floor_id=floor_id)

    registry = _TrackedRegistry()
    e0 = registry.async_create("Building - Floor - Room C", floor_id="floor_1")
    e1 = registry.async_create("Building - Floor - Room D", floor_id="floor_1")
    original_d = _FakeAreaEntry(e1.id, "Building - Floor - Room D", "floor_old")

    view = HaRoomsSyncAPIView.__new__(HaRoomsSyncAPIView)
    applied = [
        ("create", e0.id, None),
        ("update", e1.id, original_d),
    ]
    view._rollback(registry, applied)

    # update (Room D) must be processed before delete (Room C)
    assert calls == [f"update:{e1.id}", f"delete:{e0.id}"]


def test_rollback_skips_update_without_original():
    """A rollback for 'update' with no original snapshot does nothing."""
    calls: list[str] = []

    class _TrackedRegistry(_FakeAreaRegistry):
        def async_update(self, area_id, *, name=None, floor_id=None, **kw):
            calls.append(f"update:{area_id}")
            super().async_update(area_id, name=name, floor_id=floor_id)

    view = HaRoomsSyncAPIView.__new__(HaRoomsSyncAPIView)
    applied = [("update", "some_area", None)]  # no original snapshot
    view._rollback(_TrackedRegistry(), applied)

    assert calls == []


def test_rollback_multiple_rooms_reversed():
    """Multiple creates are rolled back in reverse order."""
    calls: list[str] = []

    class _TrackedRegistry(_FakeAreaRegistry):
        def async_delete(self, area_id):
            calls.append(f"delete:{area_id}")
            super().async_delete(area_id)

    registry = _TrackedRegistry()
    e0 = registry.async_create("B - F - Room 0", floor_id="f0")
    e1 = registry.async_create("B - F - Room 1", floor_id="f0")
    e2 = registry.async_create("B - F - Room 2", floor_id="f0")

    view = HaRoomsSyncAPIView.__new__(HaRoomsSyncAPIView)
    applied = [
        ("create", e0.id, None),
        ("create", e1.id, None),
        ("create", e2.id, None),
    ]
    view._rollback(registry, applied)

    assert calls == [
        f"delete:{e2.id}",
        f"delete:{e1.id}",
        f"delete:{e0.id}",
    ]


# ---------------------------------------------------------------------------
# Test suite registration
# ---------------------------------------------------------------------------

SUITE_LABEL = "🚪 HA Rooms Controller Tests"
TEST_SUITE = [
    ("registry create auto-generates area id", test_registry_create_auto_generates_id),
    ("registry create with floor_id", test_registry_create_with_floor_id),
    ("registry get_area_by_name missing", test_registry_get_area_by_name_missing),
    ("rollback deletes created areas", test_rollback_deletes_created_areas),
    ("rollback restores updated areas", test_rollback_restores_updated_areas),
    ("rollback is reversed order", test_rollback_is_reversed_order),
    ("rollback skips update without original", test_rollback_skips_update_without_original),
    ("rollback multiple rooms reversed", test_rollback_multiple_rooms_reversed),
    ("compute_area_id basic", test_compute_area_id_basic),
    ("slugify fallback ascii", test_slugify_fallback_ascii),
    ("compute_area_id special chars", test_compute_area_id_special_chars),
    ("registry create then update name keeps id", test_registry_create_then_update_name_keeps_id),
    ("compute_area_id matches registry create id", test_compute_area_id_matches_registry_create_id),
    ("registry get_area by id found", test_registry_get_area_by_id_found),
    ("registry get_area missing", test_registry_get_area_missing),
    ("duplicate name detection", test_duplicate_name_detection),
    ("unique name not marked duplicate", test_unique_name_not_marked_duplicate),
]
